#!/usr/bin/env bash

set -Eeuo pipefail

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

cd "$script_dir/wrapper"
yarn install
yarn generate

cd "$script_dir/client"
yarn install
yarn run ts-node index.ts